<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>SobekCM.Engine_Library.Tests</RootNamespace>
    <AssemblyName>SobekCM_Engine_Library.Tests</AssemblyName>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NUnit" Version="3.14.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.5.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="FsCheck" Version="2.16.6" />
    <PackageReference Include="FsCheck.NUnit" Version="2.16.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SobekCM_Engine_Library\SobekCM_Engine_Library.csproj" />
    <ProjectReference Include="..\SobekCM_Resource_Database\SobekCM_Resource_Database.csproj" />
    <ProjectReference Include="..\SobekCM_Core\SobekCM_Core.csproj" />
    <ProjectReference Include="..\EngineAgnosticLayerDbAccess\EngineAgnosticLayerDbAccess.csproj" />
  </ItemGroup>
</Project>
